name: 'Dispatch Workflow Action'
description: 'Dispatch Github Action Workflow'

inputs:
  token: 
    description: 'GitHub Token with write access'
    required: true
  workflowRef: 
    description: 'Worflow Name, Filename or ID to run'
    required: true
  inputs:
    description: 'Properties to pass to the workflow in JSON format'
    required: false
  ref:
    description: 'The git reference for the desired workflow to run. The reference can be a branch or tag name. Default is current default branch of ref'
    required: false
  repo:
    description: 'Repo owner & name, slash separated, only set if invoking a workflow in a different repo'
    required: false 

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  color: blue
  icon: book
