name: 'Trigger Open PR workflow'
description: 'Trigger Open PR workflow'

inputs:
  token:
    description: 'GitHub Token with write access'
    required: true
  workflow_filename:
    description: 'Workflow Filename'
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  color: blue
  icon: book